org.gradle.jvmargs=-Xmx2G
org.gradle.workers.max=2
minecraft_version=1.21.1
loader_version=0.16.14
mod_version=4.1.0
mod_prerelease=backport.1
maven_group=org.edtp
archives_base_name=ChainVeinFabric
fabric_version=0.116.12+1.21.1
malilib_version=0.21.10
litematica_version=0.19.61
mod_menu_version=11.0.3
